services:
  - type: web
    name: jk-client-portal
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /accounts/login/
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,client.jayeshkaremore.dev"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
